version: '3.8'

services:
  fence-test-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY_AUTH=your-secret-api-key-here
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
