services:
  # Hardhat blockchain node
  hardhat-node:
    build:
      context: .
      dockerfile: docker/Dockerfile.hardhat
    ports:
      - "8545:8545"
    volumes:
      - ./contracts:/app/contracts:ro
      - ./deploy:/app/deploy:ro
      - ./hardhat.config.js:/app/hardhat.config.js:ro
      - ./.env:/app/.env
      - hardhat_cache:/app/cache
      - hardhat_deployments:/app/deployments
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8545 && test -f /app/.hardhat-ready"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  # FastAPI application
  fence-test-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY_AUTH=${API_KEY_AUTH:-your-secret-api-key-here}
      - DEBUG=${DEBUG:-true}
      - PYTHONPATH=/app
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL:-http://hardhat-node:8545}
      - HARDHAT_PRIVATE_KEY=${PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
    volumes:
      - ./app:/app/app:ro
      - hardhat_deployments:/app/deployments:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      hardhat-node:
        condition: service_healthy
    restart: unless-stopped

volumes:
  hardhat_cache:
  hardhat_deployments:
